stages:
  - ci
  - release

default:
  image: python:3.11

ci:
  stage: ci
  image: python:$PYTHON_VERSION
  parallel:
    matrix:
      - PYTHON_VERSION:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
  interruptible: true
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
    - master
    - merge_requests
  script:
    - env | sort
    - make dev
    - make lint test docs build
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

lint_title:
  stage: ci
  interruptible: true
  only:
    - merge_requests
  script:
    - |
      if ! echo "$CI_MERGE_REQUEST_TITLE" | grep -Pq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(\w+\))?!?:\s.*"; then
        echo "The title does not conform to the Conventional Commit."
        echo "Please refer to 'https://www.conventionalcommits.org/'"
        exit 1
      fi

package:
  stage: release
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  variables:
    TWINE_NON_INTERACTIVE: 'true'
  script:
    - env | sort
    - make dev-package
    - make build
    - make upload

pages:
  stage: release
  only:
    changes:
      - docs/**/*
    refs:
      - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  except:
    refs:
      - schedules
  script:
    - env | sort
    - make dev-docs
    - make docs
  artifacts:
    paths:
      - public

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - /^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$/
  script:
    - env | sort
  release:
    description: $CI_COMMIT_TAG_MESSAGE
    name: $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
